### ISSUE TITLE
Video plays at 2x speed

### ISSUE THREAD

**Issue by danielpaulwill** [learn-co-curriculum/phase-1-lecture-videos-map#1]
## Link to Canvas
https://learning.flatironschool.com/courses/4321/pages/video-map?module_item_id=270813

## Describe the bug
The video on this page speeds up to 2x speed at 11:00. I checked that it's not a vimeo issue.

**Comment by crutell331** [comment]
Thank you for flagging this @danielpaulwill! We'll fix this issue as soon as we can.
