### ISSUE TITLE
[SE Issue] 

### ISSUE THREAD

**Issue by Haarika701** [learn-co-curriculum/phase-1-lecture-videos-map#4]
### Canvas Link

https://learning.flatironschool.com/courses/4384/pages/video-map?module_item_id=297238

### Concern

Video 's audio went upto 2x speed from 11:34  min till the end. I thought I increased the speed by mistake but it turns out it was rendered up to 2x where the actual topic starts which was difficult to understand and had to use the resource link instead for better explanation. Please fix the video. 

### Suggested Changes

This topic requires explanation more on how map method works with array iteration.

**Comment by ihollander** [comment]
Hi @Haarika701 - thanks for flagging! Another student flagged this as well in #3 so we'll use that issue to provide updates.
