### ISSUE TITLE
Video and title are not related?

### ISSUE THREAD

**Issue by gmd298** [learn-co-curriculum/phase-1-lecture-videos-map#6]
### Canvas Link

https://learning.flatironschool.com/courses/5171/pages/video-map?module_item_id=375739

### Concern

I just finished watching the video. I am very confused. .map() was never used in this video. Am I missing something here?

### Additional Context

https://vimeo.com/638001800?embedded=true&source=vimeo_logo&owner=106070186

### Suggested Changes

Include a video where the instructor actually uses .map() or change the title to accurately reflect the content. Perhaps a description about how this is or is not related to .map()?

**Comment by lizbur10** [comment]
Hi there! Thanks for bringing this to our attention. I've added an explanation to clarify what this video is doing. Apologies for the confusion 💙
